services:
  blockchain-challenge-hello:
    build: hello
    image: paradigmctf-chal-hello:latest
    container_name: blockchain-infra-challenge-hello
    restart: unless-stopped
    ports:
      - "31337:1337"
    networks:
      - default
      - ctf_network  # in order to talk to orchestrator
      - instances_network  # in order to talk to challenge
    environment:
      - "CHALLENGE=hello"
      - "FLAG=cr3{paradigm_ctf_hello_world}"
      - "PUBLIC_HOST=http://127.0.0.1:8545"
      - "ENV=local"
    depends_on:
      - ctf-server-orchestrator
  blockchain-challenge-extra-methods:
    build: extra-methods
    image: paradigmctf-chal-extra-methods:latest
    container_name: blockchain-infra-challenge-extra-methods
    restart: unless-stopped
    ports:
      - "31338:1337"
    networks:
      - default
      - ctf_network  # in order to talk to orchestrator
      - instances_network  # in order to talk to challenge
    environment:
      - "CHALLENGE=extra-methods"
      - "FLAG=cr3{extra_methods}"
      - "PUBLIC_HOST=http://127.0.0.1:8545"
      - "ENV=local"
    depends_on:
      - ctf-server-orchestrator
  blockchain-challenge-hello-api:
    image: paradigmctf-chal-hello:latest
    container_name: blockchain-infra-challenge-hello-api
    restart: unless-stopped
    ports:
      - "31339:1337"
    networks:
      - default
      - ctf_network  # in order to talk to orchestrator
      - instances_network  # in order to talk to challenge
    environment:
      - "CHALLENGE=hello-api"
      - "FLAG=cr3{paradigm_ctf_hello_api}"
      - "PUBLIC_HOST=http://127.0.0.1:8545"
      - "LAUNCHER_MODE=api"
    depends_on:
      - ctf-server-orchestrator
